services:
  - type: web
    name: prediction-markets-strapi
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true
